src/ProjetoAspNetCore.Mvc/Controllers/CidController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ProjetoAspNetCore.Aplicacao.Extensions;
using ProjetoAspNetCore.Domain.Entities;
using ProjetoAspNetCore.Data.ORM;
using System.Text;
using X.PagedList;
using System;

namespace ProjetoAspNetCore.Mvc.Controllers
{
    public class CidController : Controller
    {
        private readonly CursoDbContext _context;

        public CidController(CursoDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? pagina, string ordenacao, string stringBusca)
        {
            const int itensPorPagina = 8;
            int numeroPagina = (pagina ?? 1);

            ViewData["ordenacao"] = ordenacao;
            ViewData["filtroAtual"] = stringBusca;

            var cids = from c in _context.Cid select c;

            #region Filtro
            if (!string.IsNullOrEmpty(stringBusca))
            {
                cids = cids.Where(s => s.Codigo.Contains(stringBusca) || s.Diagnostico.Contains(stringBusca));
            }
            #endregion

            #region Ordenação
            ViewData["OrderByInternalId"] = string.IsNullOrEmpty(ordenacao) ? "CidInternalId_desc" : "";
            ViewData["OrderByCodigo"] = ordenacao == "Codigo" ? "Codigo_desc" : "Codigo";
            ViewData["OrderByDiagnostico"] = ordenacao == "Diagnostico" ? "Diagnostico_desc" : "Diagnostico";

            if (string.IsNullOrEmpty(ordenacao))
            {
                ordenacao = "CidInternalId";
            }
            if (ordenacao.EndsWith("_desc"))
            {
                ordenacao = ordenacao.Substring(0, ordenacao.Length - 5);
                cids = cids.OrderByDescending(x => EF.Property<object>(x, ordenacao));
            }
            else
            {
                cids = cids.OrderBy(x => EF.Property<object>(x, ordenacao));
            }
            #endregion
            return View(await cids.AsNoTracking().ToPagedListAsync(numeroPagina, itensPorPagina));
        }

        [HttpPost]
        public async Task<IActionResult> ImportCid(IFormFile file, [FromServices] IWebHostEnvironment webHostEnvironment)
        {
            #region Validando o arquivo
            if (!ArquivoValido.EhValido(file, "Cid.csv"))
            {
                return RedirectToAction("ArquivoInvalido");
            }
            #endregion

            string filePath = $"{webHostEnvironment.WebRootPath}\\importFiles\\{file.FileName}";
            CopiarArquivo.Copiar(file, filePath);

            #region Gravação dos registros na base
            int k = 0;
            string linha;
            List<Cid> listaDeCids = new List<Cid>();
            using (FileStream fileStream = System.IO.File.OpenRead(filePath))
            {
                using (StreamReader streamReader = new StreamReader(fileStream, encoding: Encoding.GetEncoding(1252), false))
                {
                    while ((linha = streamReader.ReadLine()) != null)
                    {
                        if (k > 0)
                        {
                            var partes = linha.Split(';');
                            if (!_context.Cid.Any(e => e.CidInternalId == int.Parse(partes[0])))
                            {
                                listaDeCids.Add(new Cid {
                                    CidInternalId = int.Parse(partes[0]),
                                    Codigo = partes[1],
                                    Diagnostico = partes[2]
                                });
                            }
                        }
                        k++;
                    }
                    if (listaDeCids.Any())
                    {
                        await _context.AddRangeAsync(listaDeCids);
                        await _context.SaveChangesAsync();
                    }
                }
            }
            #endregion

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ArquivoInvalido()
        {
            TempData["arquivoInvalido"] = "O arquivo não é válido";
            return View();
        }
        // CRUD Aqui
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {

            var cid = await _context.Cid.FirstOrDefaultAsync(m => m.Id == id);
            if (cid == null) return NotFound();

            return View(cid);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cid cid)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(cid);
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cid);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var cid = await _context.Cid.FindAsync(id);
            if (cid == null) return NotFound();

            return View(cid);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Cid cid)
        {
            if (id != cid.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CidExists(cid.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cid);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var cid = await _context.Cid.FirstOrDefaultAsync(m => m.Id == id);
            if (cid == null) NotFound();

            return View(cid);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cid = await _context.Cid.FindAsync(id);
            _context.Cid.Remove(cid);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CidExists(Guid id)
        {
            return _context.Cid.Any(x => x.Id == id);
        }
    }
}

src/ProjetoAspNetCore.Mvc/Controllers/ConfigController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoAspNetCore.Aplicacao.Extensions;
using ProjetoAspNetCore.Data.ORM;
using ProjetoAspNetCore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace ProjetoAspNetCore.Mvc.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class ConfigController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult MenuConfig()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ImportarCid()
        {
            return View();
        }


        [HttpGet]
        public IActionResult ImportarGenericos()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ImportMedicamentos([FromServices] CursoDbContext context)
        {
            string filePath = ImportUtils.GetFilePath("Csv", "Medicamentos", ".CSV");
            ReadWriteFile readWriteFile = new ReadWriteFile();
            if (!await readWriteFile.ReadAndWriteCsvAsync(filePath, context))
            {
                return View("JaTemMedicamento", context.Medicamento.AsNoTracking().OrderBy(o=>o.Codigo));
            }
            return View("Medicamentos", context.Medicamento.AsNoTracking().OrderBy(o => o.Codigo));
        }
    }
}

src/ProjetoAspNetCore.Mvc/Controllers/GenericoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoAspNetCore.Data.ORM;
using ProjetoAspNetCore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoAspNetCore.Mvc.Controllers
{
    public class GenericoController : Controller
    {
        private readonly CursoDbContext _context;

        public GenericoController(CursoDbContext context)
        {
            _context = context;
        }

        //[Route("lista-de-genericos")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var listGenerico = await _context.Generico.AsNoTracking()
                .OrderBy(o => o.Codigo)
                .ToListAsync();
            return View(listGenerico);
        }

        //[Route("detalhe-de-generico/{id:guid}")]
        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id.Value == null)
            {
                return NotFound();
            }

            var generico = await _context.Generico
                .FirstOrDefaultAsync(m => m.Id == id);
            if (generico == null)
            {
                return NotFound();
            }

            return View(generico);
        }

        //[Route("adicionar-generico")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //[Route("adicionar-generico")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Generico generico)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //generico.Id = Guid.NewGuid();
                    _context.Add(generico);
                    await _context.SaveChangesAsync();
                }
                catch (Exception e)
                {
                    throw new Exception(e.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(generico);
        }

        //[Route("editar-generico/{id:guid}")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var generico = await _context.Generico.FindAsync(id);
            if (generico == null)
            {
                return NotFound();
            }
            return View(generico);
        }


        //[Route("editar-generico/{id:guid}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Generico generico)
        {
            if (id != generico.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(generico);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenericoExists(generico.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(generico);
        }

        //[Route("excluir-generico/{id:guid}")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var generico = await _context.Generico
                .FirstOrDefaultAsync(m => m.Id == id);
            if (generico == null)
            {
                return NotFound();
            }

            return View(generico);
        }

        //[Route("excluir-generico/{id:guid}"), ActionName("Delete")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var generico = await _context.Generico.FindAsync(id);
            _context.Generico.Remove(generico);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenericoExists(Guid id)
        {
            return _context.Generico.Any(e => e.Id == id);
        }


        [HttpPost]
        public IActionResult ImportGenerico(IFormFile file)
        {
            return View();
        }
    }
}

src/ProjetoAspNetCore.Mvc/Views/Config/ImportarCid.cshtml
@model IEnumerable<ProjetoAspNetCore.Domain.Entities.Medicamento>

@{ ViewData["Title"] = "Importar Cid"; }

<vc:cabecalho titulo="SysMed - Controle hospitalar simples" subtitulo="Configyrações"></vc:cabecalho>
<div class="row" style="margin-top: 12px;">
    <div class="col-lg-12">
        <p>
            @Html.ActionLink("Config", "Index", "Config", null, new { @class = "btn btn-default" })
        </p>

        <div class="animated fadeInRightBig">
            <div class="panel panel-primary toggle">
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="fa fa-magic"></i>MedicalSystem - @ViewData["Title"]</h4>
                </div>
                <div class="panel-body">
                    <form asp-controller="Cid" asp-action="ImportCid" name="ImportCid" method="post"
                          enctype="multipart/form-data">
                        <input type="file" name="file" />
                        <hr />
                        <input type="submit" name="submit" id="submitCid" value="Carregar..." class="btn btn-info" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/ProjetoAspNetCore.Mvc/Views/Config/ImportarGenericos.cshtml
@{ ViewData["Title"] = "Importar Genéricos"; }

<vc:cabecalho titulo="SysMed - Controle hospitalar simples" subtitulo="Importação de Genéricos"></vc:cabecalho>
<div class="row" style="margin-top: 12px;">
    <div class="col-lg-12">
        <p>
            @Html.ActionLink("Config", "Index", "Config", null, new { @class = "btn btn-default" })
        </p>

        <div class="animated fadeInRightBig">
            <div class="panel panel-primary toggle">
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="fa fa-magic"></i>MedicalSystem - @ViewData["Title"]</h4>
                </div>
                <div class="panel-body">
                    <form asp-controller="Generico" asp-action="ImportGenerico" name="ImportGenerico" method="post"
                          enctype="multipart/form-data">
                        <input type="file" name="file" />
                        <hr />
                        <input type="submit" name="submit" id="submitGenerico" value="Carregar..." class="btn btn-info" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/ProjetoAspNetCore.Mvc/Views/Config/Index.cshtml
<div class="row" style="margin-top: 12px;">
    <div class="col-lg-12">
        <p>
            @Html.ActionLink("Config", "Index", "Config", null, new { @class = "btn btn-default" })
        </p>

        <div class="animate fadeInRightBig">
            <div class="panel panel-primary toggle">
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="fa fa-magic"></i>MedicalSystem - Configurações</h4>
                </div>
                <div class="panel-body">
                    <div class="jumbotron">
                        <a asp-controller="Config" asp-action="ImportMedicamentos" class="btn btn-info">Importar Medicamentos</a>
                        <a asp-controller="Config" asp-action="" class="btn btn-info">Importar Genérico</a>
                        <a asp-controller="Config" asp-action="" class="btn btn-info">Importar Cid</a>
                        <a asp-controller="Config" asp-action="" class="btn btn-info">Importar Bairro</a>
                        <a asp-controller="Config" asp-action="" class="btn btn-info">Importar Cidade</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/ProjetoAspNetCore.Mvc/Views/Config/JaTemMedicamento.cshtml
@model IEnumerable<ProjetoAspNetCore.Domain.Entities.Medicamento>



<div class="row" style="margin-top: 12px;">



    <div class="col-lg-12">

        <div class="animated fadeInRightBig">
            <div class="panel panel-primary toggle">
                <!-- Start .panel -->
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="fa fa-magic"></i> MedicalManagement-Sys - Lista de Medicamentos</h4>
                </div>
                <div class="panel-body">

                    <div class="jumbotron">
                        <h3 class="alert alert-info">Os medicamantos Já foram importados!</h3>
                    </div>

                    <listar-dados Items="@Model"></listar-dados>


                </div>
            </div>
        </div>
    </div>
</div>

<!--
<div class="modal fade modal-style4"
     id="modalGnerico"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true">

</div>

    -->

<div class="modal fade modal-style6"
     id="modalGnerico"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true">

</div>


@section Scripts{

    <script src="~/bundle/dataTables.min.js"></script>

    <script type="text/javascript">

        $(".details").click(function () {
            var id = $(this).attr("data-id");
            $("#modalGnerico").load("/Generico/Details?id=" + id, function () {
                $("#modalGnerico").modal();
            });
        });

        $(".delete").click(function () {
            var id = $(this).attr("data-id");
            $("#modalGnerico").load("/Generico/Delete?id=" + id, function () {
                $("#modalGnerico").modal();
            });
        });

        $(".edit").click(function () {
            var id = $(this).attr("data-id");
            $("#modalGnerico").load("/Generico/Edit?id=" + id, function () {
                $("#modalGnerico").modal();
            });
        });

        $(".create").click(function () {
            $("#modalGnerico").load("/Generico/Create", function () {
                $("#modalGnerico").modal();
            });
        });

    </script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                dom: 'T<"clear">lfrtip',
                tableTools: {
                    "sSwfPath": "/myPlugins/copy_csv_xls_pdf.swf"
                }
            });
        });
    </script>
}

src/ProjetoAspNetCore.Mvc/Views/Config/Medicamentos.cshtml
@model IEnumerable<ProjetoAspNetCore.Domain.Entities.Medicamento>

@{
    ViewData["Title"] = "Medicamentos";
}

<vc:cabecalho titulo="SysMed - Controle hospitalar simples" subtitulo="Cadastro de Medicamentos"></vc:cabecalho>

<div class="row" style="margin-top: 12px;">
    <div class="col-lg-12">
        <p>
            <button class="btn btn-default create" data-toggle="tooltip" data-placement="bottom" title="Adicionar um novo Medicamento" data-original-title="Adicionar um novo genérico">
                <i class="glyphicon glyphicon-plus-sign"></i>
            </button>
            <a asp-controller="Home" asp-action="Dashboard" class="btn btn-default">Home</a>
        </p>

        <div class="animated fadeInRightBig">
            <div class="panel panel-primary toggle">
                <!-- Start .panel -->
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="fa fa-magic"></i> MédicalSystem - Cadastro de Medicamentos</h4>
                </div>
                <div class="panel-body">
                    <listar-dados Items="@Model"></listar-dados>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-style6"
     id="modalGnerico"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true">

</div>


@section Scripts{

    <script src="~/bundle/dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                dom: 'T<"clear">lfrtip',
                tableTools: {
                    "sSwfPath": "/myPlugins/copy_csv_xls_pdf.swf"
                }
            });
        });
    </script>
}

src/ProjetoAspNetCore.Mvc/Views/Config/MenuConfig.cshtml
@{ ViewData["Title"] = "Configurações"; }

<vc:cabecalho titulo="SysMed - Controle hospitalar simples" subtitulo="@ViewData["Title"]"></vc:cabecalho>

<div class="row" style="margin-top: 12px;">
    <div class="col-lg-12">
        <p>
            @Html.ActionLink("Home", "Index", "Home", null, new { @class = "btn btn-default" })
        </p>

        <div class="animated fadeInRightBig">
            <div class="panel panel-primary toggle">
                <div class="panel-heading">
                    <h4 class="panel-title"><i class="fa fa-magic"></i>MedicalSystem - Configurações</h4>
                </div>
                <div class="panel-body">
                    <div class="jumbotron">
                        <a asp-controller="Config" asp-action="ImportMedicamentos" class="btn btn-info">Importar Medicamentos</a>
                        <a asp-controller="Config" asp-action="ImportarGenericos" class="btn btn-info">Importar Genérico</a>
                        <a asp-controller="Config" asp-action="ImportarCid" class="btn btn-info">Importar Cid</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>