src/ProjetoAspNetCore.Mvc/Controllers/CidController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ProjetoAspNetCore.Aplicacao.Extensions;
using ProjetoAspNetCore.Domain.Entities;
using ProjetoAspNetCore.Data.ORM;
using System.Text;
using X.PagedList;
using System;

namespace ProjetoAspNetCore.Mvc.Controllers
{
    public class CidController : Controller
    {
        private readonly CursoDbContext _context;

        public CidController(CursoDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? pagina, string ordenacao, string stringBusca)
        {
            const int itensPorPagina = 8;
            int numeroPagina = (pagina ?? 1);

            ViewData["ordenacao"] = ordenacao;
            ViewData["filtroAtual"] = stringBusca;

            var cids = from c in _context.Cid select c;

            #region Filtro
            if (!string.IsNullOrEmpty(stringBusca))
            {
                cids = cids.Where(s => s.Codigo.Contains(stringBusca) || s.Diagnostico.Contains(stringBusca));
            }
            #endregion

            #region Ordenação
            ViewData["OrderByInternalId"] = string.IsNullOrEmpty(ordenacao) ? "CidInternalId_desc" : "";
            ViewData["OrderByCodigo"] = ordenacao == "Codigo" ? "Codigo_desc" : "Codigo";
            ViewData["OrderByDiagnostico"] = ordenacao == "Diagnostico" ? "Diagnostico_desc" : "Diagnostico";

            if (string.IsNullOrEmpty(ordenacao))
            {
                ordenacao = "CidInternalId";
            }
            if (ordenacao.EndsWith("_desc"))
            {
                ordenacao = ordenacao.Substring(0, ordenacao.Length - 5);
                cids = cids.OrderByDescending(x => EF.Property<object>(x, ordenacao));
            }
            else
            {
                cids = cids.OrderBy(x => EF.Property<object>(x, ordenacao));
            }
            #endregion
            return View(await cids.AsNoTracking().ToPagedListAsync(numeroPagina, itensPorPagina));
        }

        [HttpPost]
        public async Task<IActionResult> ImportCid(IFormFile file, [FromServices] IWebHostEnvironment webHostEnvironment)
        {
            #region Validando o arquivo
            if (!ArquivoValido.EhValido(file, "Cid.csv"))
            {
                return RedirectToAction("ArquivoInvalido");
            }
            #endregion

            string filePath = $"{webHostEnvironment.WebRootPath}\\importFiles\\{file.FileName}";
            CopiarArquivo.Copiar(file, filePath);

            #region Gravação dos registros na base
            int k = 0;
            string linha;
            List<Cid> listaDeCids = new List<Cid>();
            using (FileStream fileStream = System.IO.File.OpenRead(filePath))
            {
                using (StreamReader streamReader = new StreamReader(fileStream, encoding: Encoding.GetEncoding(1252), false))
                {
                    while ((linha = streamReader.ReadLine()) != null)
                    {
                        if (k > 0)
                        {
                            var partes = linha.Split(';');
                            if (!_context.Cid.Any(e => e.CidInternalId == int.Parse(partes[0])))
                            {
                                listaDeCids.Add(new Cid {
                                    CidInternalId = int.Parse(partes[0]),
                                    Codigo = partes[1],
                                    Diagnostico = partes[2]
                                });
                            }
                        }
                        k++;
                    }
                    if (listaDeCids.Any())
                    {
                        await _context.AddRangeAsync(listaDeCids);
                        await _context.SaveChangesAsync();
                    }
                }
            }
            #endregion

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ArquivoInvalido()
        {
            TempData["arquivoInvalido"] = "O arquivo não é válido";
            return View();
        }
        // CRUD Aqui
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {

            var cid = await _context.Cid.FirstOrDefaultAsync(m => m.Id == id);
            if (cid == null) return NotFound();

            return View(cid);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cid cid)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(cid);
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cid);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var cid = await _context.Cid.FindAsync(id);
            if (cid == null) return NotFound();

            return View(cid);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Cid cid)
        {
            if (id != cid.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CidExists(cid.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cid);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var cid = await _context.Cid.FirstOrDefaultAsync(m => m.Id == id);
            if (cid == null) NotFound();

            return View(cid);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cid = await _context.Cid.FindAsync(id);
            _context.Cid.Remove(cid);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CidExists(Guid id)
        {
            return _context.Cid.Any(x => x.Id == id);
        }
    }
}

src/ProjetoAspNetCore.Mvc/Controllers/ConfigController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoAspNetCore.Aplicacao.Extensions;
using ProjetoAspNetCore.Data.ORM;
using ProjetoAspNetCore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace ProjetoAspNetCore.Mvc.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class ConfigController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult MenuConfig()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ImportarCid()
        {
            return View();
        }


        [HttpGet]
        public IActionResult ImportarGenericos()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ImportMedicamentos([FromServices] CursoDbContext context)
        {
            string filePath = ImportUtils.GetFilePath("Csv", "Medicamentos", ".CSV");
            ReadWriteFile readWriteFile = new ReadWriteFile();
            if (!await readWriteFile.ReadAndWriteCsvAsync(filePath, context))
            {
                return View("JaTemMedicamento", context.Medicamento.AsNoTracking().OrderBy(o=>o.Codigo));
            }
            return View("Medicamentos", context.Medicamento.AsNoTracking().OrderBy(o => o.Codigo));
        }
    }
}

src/ProjetoAspNetCore.Mvc/Controllers/EstadoPacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoAspNetCore.Data.ORM;
using ProjetoAspNetCore.Domain.Entities;

namespace ProjetoAspNetCore.Mvc.Controllers
{
    public class EstadoPacienteController : Controller
    {
        private readonly CursoDbContext _context;

        public EstadoPacienteController(CursoDbContext context)
        {
            _context = context;
        }

        // GET: EstadoPaciente
        public async Task<IActionResult> Index()
        {
            return View(await _context.EstadoPaciente.ToListAsync());
        }

        // GET: EstadoPaciente/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadoPaciente = await _context.EstadoPaciente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estadoPaciente == null)
            {
                return NotFound();
            }

            return View(estadoPaciente);
        }

        // GET: EstadoPaciente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EstadoPaciente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descricao,Id")] EstadoPaciente estadoPaciente)
        {
            if (ModelState.IsValid)
            {
                estadoPaciente.Id = Guid.NewGuid();
                _context.Add(estadoPaciente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estadoPaciente);
        }

        // GET: EstadoPaciente/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadoPaciente = await _context.EstadoPaciente.FindAsync(id);
            if (estadoPaciente == null)
            {
                return NotFound();
            }
            return View(estadoPaciente);
        }

        // POST: EstadoPaciente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Descricao,Id")] EstadoPaciente estadoPaciente)
        {
            if (id != estadoPaciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estadoPaciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadoPacienteExists(estadoPaciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estadoPaciente);
        }

        // GET: EstadoPaciente/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadoPaciente = await _context.EstadoPaciente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estadoPaciente == null)
            {
                return NotFound();
            }

            return View(estadoPaciente);
        }

        // POST: EstadoPaciente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var estadoPaciente = await _context.EstadoPaciente.FindAsync(id);
            _context.EstadoPaciente.Remove(estadoPaciente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadoPacienteExists(Guid id)
        {
            return _context.EstadoPaciente.Any(e => e.Id == id);
        }
    }
}

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_estado_paciente.cshtml
<div class="panel panel-info">

    <div class="panel panel-heading"><h4>Estado dos Pacientes</h4></div>

    <div class="panal panel-body">

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-critico></vc:estado-critico>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-estavel></vc:estado-estavel>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-grave></vc:estado-grave>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-observacao-view-components></vc:estado-observacao-view-components>
        </div>

    </div>

</div>

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_footer.cshtml
<div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
        Copyrights &copy; 2014 / @DateTime.Now.Year.ToString() <a href="http://eaditdeveloper.com.br/" class="color-blue strong" target="_blank">EAD IT Developer</a>. Todos os direitos reservados.
    </p>
    <p>
        &nbsp; <email dominio="gmail.com">contato</email>  -  <email>contato</email>   
    </p>

</div>
<!-- End #footer  -->

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_head.cshtml
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - EAD Médicina</title>
    <!-- Mobile specific metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no">
    <!-- Force IE9 to render in normal mode -->
    <!--[if IE]><meta http-equiv="x-ua-compatible" content="IE=9" /><![endif]-->
    <meta name="author" content="" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="application-name" content="" />
    <!-- Import google fonts - Heading first/ text second -->
    @*<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700' rel='stylesheet' type='text/css'>*@

    <!-- Css files -->
    <!-- Icons -->
    <link href="~/bundle/core.min.css" rel="stylesheet" />

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/ico/apple-touch-icon-57-precomposed.png">
    <link rel="icon" href="img/ico/favicon.ico" type="image/png">
    <!-- Windows8 touch icon ( http://www.buildmypinnedsite.com/ )-->
    <meta name="msapplication-TileColor" content="#3399cc" />
</head>

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_lis_menu_left.cshtml
<li>
    <a asp-controller="Home" asp-action="Index"><i class="l-basic-home"></i><span class="txt">Home</span></a>
</li>

<li>
    <a asp-controller="Home" asp-action="Dashboard"><i class="l-basic-laptop"></i><span class="txt">Dashboard</span></a>
</li>

<li>
    <a href="#"><i class="l-ecommerce-graph3"></i><span class="tex">Cadastro</span></a>
    <ul class="sub">
        <li>
            <a asp-controller="Paciente" asp-action="Index"><i class="l-basic-alarm"></i><span class="txt">Paciente</span></a>
        </li>

        <li>
            <a asp-controller="Generico" asp-action="Index"><i class="l-basic-info"></i><span class="txt">Genéricos</span></a>
        </li>

        <li>
            <a asp-controller="Cid" asp-action="Index"><i class="l-basic-cards-hearts"></i><span class="txt">Lista CID</span></a>
        </li>
    </ul>
</li>


<li>
    <a asp-controller="Config" asp-action="MenuConfig"><i class="l-basic-todo-pen"></i><span class="txt">Config</span></a>
</li>




<li>
    <a href="#"><i class="l-basic-accelerator"></i> <span class="txt">Reflection</span></a>
    <ul class="sub">
        <li><a asp-controller="EstadoPaciente" asp-action="Index"><span class="txt">Est. Paciente</span></a></li>
        <li><a asp-controller="Paciente" asp-action="PacienteReflection"><span class="txt">Paciente</span></a></li>
    </ul>
</li>



























@* Links originais da template *@


@*<li>
        <a href="#"><i class="l-ecommerce-graph1"></i> <span class="txt">Charts</span></a>
        <ul class="sub">
            <li>
                <a href="charts-flot.html"><span class="txt">Flot charts</span></a>
            </li>
            <li>
                <a href="charts-morris.html"><span class="txt">Morris charts</span></a>
            </li>
            <li>
                <a href="charts-chartjs.html"><span class="txt">Chartjs </span></a>
            </li>
            <li>
                <a href="charts-other.html"><span class="txt">Other charts</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-basic-webpage-txt"></i><span class="txt">Forms</span></a>
        <ul class="sub">
            <li>
                <a href="forms-basic.html"><span class="txt">Basic forms</span></a>
            </li>
            <li>
                <a href="forms-advanced.html"><span class="txt">Advanced forms</span></a>
            </li>
            <li>
                <a href="forms-layouts.html"><span class="txt">Form layouts</span></a>
            </li>
            <li>
                <a href="forms-wizard.html"><span class="txt">Form wizard</span></a>
            </li>
            <li>
                <a href="forms-validation.html"><span class="txt">Form validation</span></a>
            </li>
            <li>
                <a href="code-editor.html"><span class="txt">Code editor</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-software-layout-header-3columns"></i><span class="txt">Tables</span></a>
        <ul class="sub">
            <li>
                <a href="tables-basic.html"><span class="txt">Basic tables</span></a>
            </li>
            <li>
                <a href="tables-data.html"><span class="txt">Data tables</span></a>
            </li>
            <li>
                <a href="tables-editable.html"><span class="txt">Editable tables</span></a>
            </li>
            <li>
                <a href="tables-ajax.html"><span class="txt">Ajax tables</span></a>
            </li>
            <li>
                <a href="tables-pricing.html"><span class="txt">Pricing tables</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-software-layers2"></i><span class="txt">UI Elements</span></a>
        <ul class="sub">
            <li>
                <a asp-controller="Home" asp-action="Icones"><span class="txt">Ícones</span></a>
            </li>
            <li>
                <a href="typography.html"><span class="txt">Typography</span></a>
            </li>
            <li>
                <a href="tabs.html"><span class="txt">Tabs</span></a>
            </li>
            <li>
                <a href="accordions.html"><span class="txt">Accordions</span></a>
            </li>
            <li>
                <a href="buttons.html"><span class="txt">Buttons</span></a>
            </li>
            <li>
                <a href="notifications.html"><span class="txt">Notifications</span></a>
            </li>
            <li>
                <a href="modals.html"><span class="txt">Modals</span></a>
            </li>
            <li>
                <a href="sliders.html"><span class="txt">Sliders</span></a>
            </li>
            <li>
                <a href="progressbars.html"><span class="txt">Progressbars</span></a>
            </li>
            <li>
                <a href="lists.html"><span class="txt">Lists</span></a>
            </li>
            <li>
                <a href="grid.html"><span class="txt">Grid</span></a>
            </li>
            <li>
                <a href="ui-other.html"><span class="txt">Other</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="portlets.html"><i class="l-software-layout-header"></i><span class="txt">Portlets</span><span class="label">22</span></a>
    </li>
    <li>
        <a href="#"><i class="l-basic-mail"></i> <span class="txt">Email</span></a>
        <ul class="sub">
            <li>
                <a href="email-inbox.html"><span class="txt">Inbox</span></a>
            </li>
            <li>
                <a href="email-read.html"><span class="txt">Read email</span></a>
            </li>
            <li>
                <a href="email-write.html"><span class="txt">Write email</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-basic-geolocalize-01"></i><span class="txt">Maps</span></a>
        <ul class="sub">
            <li>
                <a href="maps-google.html"><span class="txt">Google maps</span></a>
            </li>
            <li>
                <a href="maps-vector.html"><span class="txt">Vector maps</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-basic-webpage"></i><span class="txt">Pages</span></a>
        <ul class="sub">
            <li>
                <a href="login.html"><span class="txt">Login</span></a>
            </li>
            <li>
                <a href="lock-screen.html"><span class="txt">Lock screen</span></a>
            </li>
            <li>
                <a href="register.html"><span class="txt">Register</span></a>
            </li>
            <li>
                <a href="lost-password.html"><span class="txt">Lost password</span></a>
            </li>
            <li>
                <a href="profile.html"><span class="txt">User profile</span></a>
            </li>
            <li>
                <a href="calendar.html"><span class="txt">Calendário</span></a>
            </li>
            <li>
                <a href="timeline.html"><span class="txt">Timeline</span></a>
            </li>
            <li>
                <a href="gallery.html"><span class="txt">Gallery</span></a>
            </li>
            <li>
                <a href="invoice.html"><span class="txt">Invoice</span></a>
            </li>
            <li>
                <a href="blank.html"><span class="txt">Blank page</span></a>
            </li>
            <li>
                <a href="#"><span class="txt">Error pages</span></a>
                <ul class="sub">
                    <li>
                        <a href="403.html"><span class="txt">403</span></a>
                    </li>
                    <li>
                        <a href="404.html"><span class="txt">404</span></a>
                    </li>
                    <li>
                        <a href="500.html"><span class="txt">500</span></a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>*@

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_menu_inferior_left.cshtml
<!--  .sidebar-panel -->
<div class="sidebar-panel">
    <h5 class="sidebar-panel-title">Server stats</h5>
    <div class="sidebar-panel-content">
        <div class="sidebar-stat mb10">
            <p class="color-white mb5 mt5">
                <i class="fa fa-hdd-o mr5"></i> Disk Space <span class="pull-right small">30%</span>
            </p>
            <div class="progress flat transparent progress-bar-xs">
                <div class="progress-bar progress-bar-white" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;"></div>
            </div>
            <span class="dib s12 mt5 per100 text-center">3001.56 / 10000 MB</span>
        </div>
        <div class="sidebar-stat">
            <p class="color-white mb5 mt5">
                <i class="glyphicon glyphicon-transfer mr5"></i> Bandwidth Transfer <span class="pull-right small">78%</span>
            </p>
            <div class="progress flat transparent progress-bar-xs">
                <div class="progress-bar progress-bar-white" role="progressbar" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100" style="width: 78%;"></div>
            </div>
            <span class="dib s12 mb10 mt5 per100 text-center">87565.12 / 120000 MB</span>
        </div>
    </div>
</div>

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_profile_left_sidebar.cshtml
<div class="sidebar-panel">
    <h5 class="sidebar-panel-title">Profile</h5>
</div>
<!-- / .sidebar-panel -->
<div class="user-info clearfix">
    <img src="~/img/avatars/foto-padrao.jpg" alt="avatar" 
         style="clear: both; float: left; margin-right: 10px; border: 2px solid #eeeeee; width: 50px; height: 50px; border-radius: 50%">
    <span class="name">SuggeElson</span>
    <div class="btn-group">
        <button type="button" class="btn btn-default btn-xs">
            <i class="l-basic-gear"></i>
        </button>
        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
            settings <span class="caret"></span>
        </button>
        <ul class="dropdown-menu right" role="menu">
            <li>
                <a href="profile.html"><i class="fa fa-edit"></i>Edit profile</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-money"></i>Windraws</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-credit-card"></i>Deposits</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="login.html"><i class="fa fa-power-off"></i>Logout</a>
            </li>
        </ul>
    </div>
</div>

src/ProjetoAspNetCore.Mvc/Views/Shared/PartialViews/_sub_navbar.cshtml
<!-- .page-content-inner -->
<div id="page-header" class="clearfix">
    <div class="page-header">
        <h2>Dashboard</h2>
        <span class="txt">Welcome to Dynamic admin</span>
    </div>
    <div class="header-stats">
        <div class="spark clearfix">
            <div class="spark-info"><span class="number">2345</span>Visitors</div>
            <div id="spark-visitors" class="sparkline"></div>
        </div>
        <div class="spark clearfix">
            <div class="spark-info"><span class="number">17345</span>Views</div>
            <div id="spark-templateviews" class="sparkline"></div>
        </div>
        <div class="spark clearfix">
            <div class="spark-info"><span class="number">3700$</span>Sales</div>
            <div id="spark-sales" class="sparkline"></div>
        </div>
    </div>
</div>